name: Licensed

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Check licenses
    steps:
      - uses: actions/checkout@v2.3.2
      - run: npm ci
      - uses: peaceiris/workflows/licensed@v0.1.0
