name: 'Suggest Related Links'

on:
  issues:
    types:
      - opened
      - edited

jobs:
  suggest:
    runs-on: ubuntu-18.04
    steps:
      - uses: peaceiris/actions-suggest-related-links@v0.4.0
