name: 'Suggest Related Links Train'

on:
  workflow_dispatch:
  schedule:
    - cron: '13 13 * * */7'

jobs:
  train:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Train
        uses: peaceiris/actions-suggest-related-links/actions/train@v0.4.0
        with:
          repository: 'peaceiris/actions-gh-pages'
