name: 'Suggest Related Links'

on:
  issues:
    types:
      - opened
      - edited
  workflow_dispatch:
  schedule:
    - cron: '13 13 * * */7'

jobs:
  action:
    runs-on: ubuntu-18.04
    steps:
      - uses: peaceiris/actions-suggest-related-links@v0.6.1
        with:
          repository: 'peaceiris/actions-gh-pages'
