name: 'Test'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'models/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'models/**'

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node/releases
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: ".nvmrc"

      - run: npm ci
      - run: npm run fmt:check
      - run: npm run lint
      - run: npm test
      - run: npm run build

      - name: Upload test coverage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

      - uses: codecov/codecov-action@v3
