name: Update major tag

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: peaceiris/workflows/update-major-tag@v0.4.0
        if: github.event.release.prerelease == false
